### ISSUE TITLE
Articles tags notify error

### ISSUE THREAD

**Issue by gravinos** [Mark-H/Notify404#13]
Hi, I get errors from pages with blog tags and archives of Articles 1.7.2, is possible disable or fix this? Thanks

**Comment by Mark-H** [comment]
Probably need to change the priority of the Notify404 plugin. Edit the
plugin and find OnPageNotFound on the system events tab. Change the
priority column from 0 to a higher number.
Op 22 jun. 2014 12:27 schreef "Gravino Design" notifications@github.com:

**Comment by gravinos** [comment]
Thanks, set to 1 and it's ok!!
