### ISSUE TITLE
listen to Redirector possible?

### ISSUE THREAD

**Issue by anselmh** [Mark-H/Notify404#6]
So if there's a rule defined in Redirector plugin that Notify404 doesn't notify of that page.

**Comment by Mark-H** [comment]
When redirector redirects a page, notify404 shouldn't be triggering at all. 

If it is, can you try to set the priority to a higher number on the System Events tab on the plugin and let me know if that fixes the issues you have? I'll have to see if I'm properly telling the build to trigger it last..

**Comment by anselmh** [comment]
That worked. You should set this to a higher number by default, was set both to '0'. And it's confusing me that prio ist set from 0->9999 whereas ACLs are 9999->0… but that's not on you.
