### ISSUE TITLE
e-mail

### ISSUE THREAD

**Issue by MrReaL** [Mark-H/Notify404#8]
Is there anyway to adjust the email after installation? Made a mistake with the email, couldn't find it anywhere so i reinstalled it.

**Comment by Mark-H** [comment]
System > System Settings, in the namespace dropdown (that defaults to
"core") choose Notify404 - there's the settings in there.
Op 15 jan. 2012 19:26 schreef "MrReaL" <
reply@reply.github.com>
het volgende:
